server:
  port: 55811

spring:
  security:
    type: NOAUTH
    jwt-bearer-token: true
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mysql_db
    username: root
    password: Bhupen15@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

infra:
  gateway:
    url: http://localhost:8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${random.number}

logging:
  level:
    root: info
  file:
    name: ${java.io.tmpdir}/${spring.application.name}.log
