server:
  port: 55813

spring:
  security:
    type: NOAUTH
  application:
    name: CUSTOMER-SERVICE
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mysql_db
    username: root
    password: Bhupen15@mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
      job:
        enabled: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

infra:
  gateway:
    url: http://localhost:8762

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${random.number}

logging:
  level:
    root: info
  file:
    name: ${java.io.tmpdir}/${spring.application.name}.log

customer:
  data:
    file:
      path: src/main/resources/customers-data.csv
      header: customerId,firstName,lastName,email,gender,contactNumber,country,dateOfBirth
    save:
      chunk:
        size: 250
