
server:
  port: 8762
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${random.number}

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**, /api/admin/**
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/customer/**
        - id: URL-SERVICE
          uri: lb://URL-SERVICE
          predicates:
            - Path=/api/url/**


logging:
  level:
    root: info
  file:
    name: ${java.io.tmpdir}/${spring.application.name}.log

