server:
  port: 8070

spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bhupendraky/bktech-config-server-properties.git
          refresh-rate: 1

management:
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

